name: Run E2E Testes

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: 'npm'

      - run: npm ci

      - name: Wait for PostgreSQL to be available"

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
