name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm' 

      - name: Install dependencies
        run: npm ci

      - name: Ensure prisma test environment exists
        run: mkdir -p prisma/vitest-environment-prisma && npm init -y --prefix prisma/vitest-environment-prisma

      - name: Install prisma test environment dependencies
        run: npm install --prefix prisma/vitest-environment-prisma

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@postgres:5432/apisolid?schema=public"
